apiVersion: v1
kind: Service
metadata:
  name: recko-service-node
spec:
  selector:
    app: recko-deployment-node
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recko-deployment-node
spec:
  selector:
    matchLabels:
      app: recko-deployment-node
  replicas: 1
  template:
    metadata:
      labels:
        app: recko-deployment-node
    spec:
      containers:
      - name: node-app
        image: "gcr.io/white-device-223818/node-image:latest"
       
