apiVersion: v1
kind: Service
metadata:
  name: recko-service-python
spec:
  selector:
    app: recko-deployment-python
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recko-deployment-python
spec:
  selector:
    matchLabels:
      app: recko-deployment-python
      # track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: recko-deployment-python
        # track: stable
    spec:
      containers:
      - name: python-app
        image: "gcr.io/white-device-223818/python-app:latest"
        # lifecycle:
        #   preStop:
        #     exec:
        #       command: ["/usr/sbin/nginx","-s","quit"]
