apiVersion: v1
kind: Service
metadata:
  name: recko-service-java
spec:
  selector:
    app: recko-deployment-java
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recko-deployment-java
spec:
  selector:
    matchLabels:
      app: recko-deployment-java
  replicas: 1
  template:
    metadata:
      labels:
        app: recko-deployment-java
    spec:
      containers:
      - name: java-app
        image: "gcr.io/white-device-223818/java-image:latest"
       
